version: "3.9"

services:
    api:
        build: .
        ports:
            - 3333:3333
        env_file:
            - ./.env
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: supersecret
            POSTGRES_USER: admin
            POSTGRES_DB: bdcp
