version: "3.9"

services:
    api:
        build: .
        ports:
            - 3000:3000
        env_file:
            - ./.env
        environment:
            - DB_HOST=mysql
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            MYSQL_ROOT_PASSWORD: supersecret
            MYSQL_DATABASE: bdcp
