version: "3.9"

services:
    api:
        build: .
        ports:
            - 3000:3000
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: supersecret
            POSTGRES_USER: admin
            POSTGRES_DB: bdcp
