name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm audit
    - run: npm run lint:check
    - run: npm run typecheck
  deploy:
    needs: build
    if: ${{ github.ref_name == 'main' || github.ref_name == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Map branch to Heroku
        shell: bash
        run: |
          env=${{ github.ref_name }}
          branch_name="dev-api-minha-disciplina"
          echo $env

          if [[ $env = "main" ]]
          then
            branch_name="api-minha-disciplina"
          else
            branch_name="dev-api-minha-disciplina"
          fi
          echo $branch_name
          echo "##[set-output name=env;]$(echo $branch_name)"
        id: app_name
      - uses: actions/checkout@v2
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and Push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ steps.app_name.outputs.env }} web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ steps.app_name.outputs.env }} web
